### PR TITLE
Add more comprehensive highlighting and an update script

### PR DESCRIPTION
**Pull request by crater2150**
I started writing a syntax file for kitty recently before finding this one. This PR contains several improvements from merging the two:

- Keywords are only matched at the start of the line (#2)
- Additional highlighting for `map` and `mouse_map`: keys are highlighted as `Constant`, the actions bound are highlighted via a separate keyword list
- Highlight unknown keywords or actions with the `Error` class
- Detect any `*.conf` files in kitty's configuration directory (#1)
- Add a script to regenerate keywords and bindable actions from kitty's python library (#3). I tried to find all sources for possible bindable actions, as these don't seem to be all in one single place in the source, so there may be some missing, but it looks like all lines from the example config are matched. The script ~requires kitty's libraries in PYTHONPATH~ should be run from the project root as `kitty +launch gen-syntax.py`. It also requires the marker comment in the syntax file to be unchanged.

As most of these changes build on one another, I put them in a single PR, but feel free to cherry-pick and leave any later commits out.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Note you dont need to have kitty in PYTHONPATH to run your script, you can simply do:

kitty +launch myscript.py

to run it

**Review by fladson — APPROVED** [review]
This is great, thank you very much for the contribution @crater2150!

**Comment by fladson** [comment]
@crater2150 any idea why these were not included with the script?
Screenshot 2021-06-28 at 16 17 51

**Comment by fladson** [comment]
The `include` is also not recognized as an option.

**Comment by fladson** [comment]
I was using `from kitty.config import option_names_for_completion` before, I will try to adapt the script to see if with that we have more options.

**Comment by kovidgoyal** [comment]
import is not an option name, you will need to hard code it. It should be syntax highlighted as Import anyway, not as a keyword.

**Comment by crater2150** [comment]
@fladson it looks like `create_marker` and `remove_marker` are remote commands only and so are not included in the lists I'm querying. But it also looks like they aren't included in `option_names_for_completion`.

I think `kitty.rc.base.all_command_names` contains the missing remote-only commands, I'll add them to the script.

**Comment by kovidgoyal** [comment]
create_marker and remove_marker are not option names, they are action names. That is, they are functions that can be mapped via map/mouse_map. kitty doesn't currently have anyway to get a comprehensive list of such function names, that's on my TODO list.

**Comment by kovidgoyal** [comment]
And I just committed code to document all mappable actions. You can get the list of actions using the get_all_actions() function in the kitty.actions module.

**Comment by fladson** [comment]
Nice, thank you @kovidgoyal for letting us know.
@crater2150 do you mind refactoring the script? With that I believe we can remove the logic to check for actions in the `definitions` and `arg_funcs`, what do you think?

**Comment by crater2150** [comment]
@fladson Sounds good, I'll look into it.

**Comment by crater2150** [comment]
I tried using `get_all_actions()` and let the script print out a comparison to the old method. There are several actions, that were included before, but not in `get_all_actions()`. Some seem to be false positives from the old method (e.g. `decrease_background_opacity` isn't an action, just a link anchor for the docs), but others (e.g. `close_tab`) are mentioned in the documentation. The ones not returned by `get_all_actions`, but by the previous method are:
```
first_window second_window third_window fourth_window fifth_window sixth_window seventh_window eighth_window ninth_window tenth_window
close_tab
debug_config
decrease_background_opacity
decrease_font_size
disable_ligatures
env
focus_tab
focus_window
full_background_opacity
get_colors
get_text
goto_file_line
increase_background_opacity
increase_font_size
insert_selected_hash
insert_selected_line
insert_selected_path
insert_selected_word
layout_action
ls
new_os_window
open_selected_hyperlink
open_selected_path
open_url
pipe
reload_config_file
reset_background_opacity
reset_font_size
reset_terminal
run_kitten
run_simple_kitten
scroll_window
set_background_image
set_font_size
set_spacing
set_window_title
```
@kovidgoyal Could you confirm if these aren't meant to be bindable to keys?

**Comment by kovidgoyal** [comment]
There were a few I missed, but yes most of them are not mappable
actions. https://github.com/kovidgoyal/kitty/commit/c6938c90390b123c57f0080ba8cbee990ad706b7

**Pull request merged**
