### PR TITLE
Sync with v0.36.2

### PR DESCRIPTION
**Pull request by warbacon**
Kitty v0.36.0 has been available since August 17 and brought some new features and thus new configuration keywords.

This PR synchronizes vim-kitty with kitty v0.36.2, released a few days ago.

[kitty changelog](https://sw.kovidgoyal.net/kitty/changelog/)

### CODE REVIEW

**Comment by warbacon** [comment]
I have decided to fork your project to try to improve it and synchronize it faster, I hope you don't mind!

**Comment by fladson** [comment]
Hey @warbacon I was off for some time and couldn't contribute much here, so I understand the fork.
If you are still interested on contributing here, I could add you as a collaborator, I liked your README improvements.

**Comment by warbacon** [comment]
That would be great! I see that you've also decided to publish releases, so there's not much point in my fork.

**Comment by fladson** [comment]
Cool, sent the invite, feel free to bring the README improvements, lets just create PRs from now on instead of merging directly into `main`.

**Comment by warbacon** [comment]
I'm on it 🫡.

**Pull request closed without merging**
